version: '3.7'
services:
  foodtracker-backend:
    image: polc/foodtracker
    container_name: foodtracker
    ports:
    - "9080:8080"
    environment:
    - DB_USER=foodtracker
    - DB_PASS=84VgKg472f2gH47Hdvn3hZ3
    - DB_URL=jdbc:mysql://mysql:3306/foodtracker
  mysql:
    image: mysql
    container_name: mysql
    volumes:
    - "./database:/var/lib/mysql"
    ports:
    - "9001:3306"
    environment:
    - MYSQL_DATABASE=foodtracker
    - MYSQL_USER=foodtracker
    - MYSQL_PASSWORD=84VgKg472f2gH47Hdvn3hZ3
    - MYSQL_ROOT_PASSWORD=84VgKg472f2gH47Hdvn3hZ3
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
    - "9000:9000"
    - "9092:9092"
